### ISSUE TITLE
no Demo?

### ISSUE THREAD

**Issue by axel-rank** [jorgetite/grav-theme-qboss#2]
Your Demo Link does not work!

![demo](https://user-images.githubusercontent.com/12480617/42840304-b03cfd22-8a06-11e8-96a1-1e2da5e11e46.png)

**Comment by diomed** [comment]
it works, but it's just under another url. this issue is already reported in #1 and  fixed.

for demo see here: http://qbee.jorgetite.com

**Comment by axel-rank** [comment]
you could set the link on the demo link of grav theme site?
