### ISSUE TITLE
Features page error on fresh install

### ISSUE THREAD

**Issue by nigelwhite** [jorgetite/grav-theme-qboss#4]
Hi. Great theme, thanks.

On fresh install the Features page gives error

RuntimeException (400) Template "features.html.twig" is not defined.

Grav 1.5.10

**Comment by jorgetite** [comment]
Hi,

Please be sure you have installed the theme by executing the following command in the root of your Grav install:

`bin/gpm install qbee`

You can use the instructions in the following post to create a modular page containing a features view:
[grav-theme-qbee/issues/3](https://github.com/jorgetite/grav-theme-qbee/issues/3)
